name: Build with Vite

on:
  pull_request:
    branches: ["master"]

  # Enable running this manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: 23.x

      - name: Build
        run: |
          ./build.sh
